env:
- TEST="ckan.tests.legacy"
- TEST="ckan.tests.logic ckan.tests.model"
- TEST="ckanext"
- TEST="ckan.tests.test_coding_standards ckan.tests.controllers ckan.tests.config ckan.tests.lib ckan.tests.i18n ckan.tests.plugins ckan.tests.test_authz ckan.tests.test_factories"

command:
- mkdir -p $CIRCLE_TEST_REPORTS/nose
- nosetests --ckan --reset-db --with-pylons=test-core.ini --nologcapture --with-coverage --cover-package=ckan --cover-package=ckanext --with-xunit --xunit-file=$CIRCLE_TEST_REPORTS/nose/junit.xml $TEST
