language: python
sudo: required
python:
  - "2.6"
  - "2.7"
env:
  global:
    - CKAN_POSTGRES_DB=ckan_test
    - CKAN_POSTGRES_USER=ckan_default
    - CKAN_POSTGRES_PWD=pass
    - CKAN_DATASTORE_POSTGRES_DB=datastore_test
    - CKAN_DATASTORE_POSTGRES_WRITE_USER=ckan_default
    - CKAN_DATASTORE_POSTGRES_READ_USER=datastore_default
    - CKAN_DATASTORE_POSTGRES_READ_PWD=pass
  matrix:
    - PGVERSION=9.1
    - PGVERSION=8.4
matrix:
  exclude:
    - python: "2.7"
      env: PGVERSION=8.4
    - python: "2.6"
      env: PGVERSION=9.1
install: ./bin/travis-install-dependencies
script: ./bin/travis-run-tests
notifications:
  irc:
    channels:
      - "irc.freenode.org#ckan"
    on_success: never
    on_failure: change
    template:
      - "%{repository} %{branch} %{commit} %{build_url} %{author}: %{message}"
after_success:
  - coveralls
