version: '2'
services:
  ckan:
    container_name: ckan
    image: ckan/ckan:latest
    depends_on:
      - db
      - solr
      - redis
    links:
       - db
       - solr
       - redis
    ports:
       - "80:5000"
  db:
    container_name: db
    image: ckan/postgresql:latest
  solr:
    container_name: solr
    image: ckan/solr:latest
  redis:
    container_name: redis
    image: redis:latest
