# docker-compose build && docker-compose up
# If you experience problems with the CKAN container not being
# able to connect to the DB, then most likely the DB has not
# started up quickly enough. Just do "docker-compose up ckan"
# again to retry
version: "3"
services:
  ckan:
    container_name: ckan
    build:
      context: ../../
      args:
        - CKAN_SITE_URL=${CKAN_SITE_URL}
    links:
      - db
      - solr
      - redis
    ports:
      - "80:5000"
    environment:
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/ckan
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - DB_PORT_5432_TCP_ADDR=db
      - DB_PORT_5432_TCP_PORT=${POSTGRES_PORT}
      - SOLR_PORT_8983_TCP_ADDR=solr
      - SOLR_PORT_8983_TCP_PORT=8983
      - REDIS_PORT_6379_TCP_ADDR=redis
      - REDIS_PORT_6379_TCP_PORT=6379
  db:
    container_name: db
    build:
      context: postgresql/
      args:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  solr:
    container_name: solr
    image: ckan/solr:latest
    ports:
      - "8983:8983"
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
