# docker-compose build && docker-compose up
ckan:
  container_name: ckan
  # Note, if you are working on CKAN core, change this to
  # build ../../
  image: ckan/ckan:latest
  links:
      - db
      - solr
      - redis
  ports:
      - "80:5000"
  environment:
      - DB_ENV_POSTGRES_USER=ckan
      - DB_ENV_POSTGRES_PASSWORD=ckan
      - DB_ENV_POSTGRES_DB=ckan
      - DB_PORT_5432_TCP_ADDR=db
      - DB_PORT_5432_TCP_PORT=5432
      - SOLR_PORT_8983_TCP_ADDR=solr
      - SOLR_PORT_8983_TCP_PORT=8983
      - REDIS_PORT_6379_TCP_ADDR=redis
      - REDIS_PORT_6379_TCP_PORT=6379

db:
  container_name: db
  build: postgresql/
  
solr:
  container_name: solr
  image: ckan/solr:latest
    
redis:
  container_name: redis
  image: redis:latest
