# docker-compose build && docker-compose up -d
# If "docker-compose logs ckan" shows DB not ready, run "docker-compose restart ckan" a few times.
version: "3.4"

volumes:
  ckan_config:
  ckan_home:
  ckan_storage:
  pg_data:
  data-volume:
  solr-volume:

services:
  ckan:
    restart: always
    container_name: ckan
    build:
      context: ../../
      args:
          - CKAN_SITE_URL=${CKAN_SITE_URL}
    links:
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
#      - "0.0.0.0:443:5000"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis or Datapusher
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
    privileged: true
    volumes:
      # - ckan_config:/etc/ckan
      # - ckan_home:/usr/lib/ckan
      # - ckan_storage:/var/lib/ckan
      - data-volume:/var/harvester

  datapusher:
    restart: always
    container_name: datapusher
    image: clementmouchet/datapusher
    ports:
      - "8800:8800"

  db:
    restart: always
    container_name: db
    build:
      context: ../../
      dockerfile: contrib/docker/postgresql/Dockerfile
      args:
        - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # command: /docker-entrypoint-initdb.d/00_create_datastore.sh
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    restart: always
    container_name: solr
    build:
      context: ../../
      dockerfile: contrib/docker/solr/Dockerfile
      args:
        - SOLR_VERSION=${SOLR_VERSION}
    ports:
      - "8983:8983"
    environment:
      - SOLR_VERSION=${SOLR_VERSION}
    volumes:
      # - solr-volume:/solr/data
      - solr-volume:/opt/solr/server/solr/ckan/data

  redis:
    restart: always
    container_name: redis
    image: redis:latest

  harvester:
    restart: always
    container_name: harvester
    build: ./harvester
    tty: true
    command: /tmp/harvester_src/src/main/scripts/do-harvester.sh
    volumes:
      - data-volume:/var/harvester
      - ckan_config:/etc/ckan
  
