version: '2'
services:
  ckan:
    container_name: ckan
    image: ckan/ckan:latest
    build: 
      context: ./../../
    depends_on:
      - db
      - solr
      - redis
    links:
       - db
       - solr
       - redis
    ports:
       - "80:5000"

  db:
    container_name: db
    image: ckan/postgresql:latest
    build:
      context: ./postgresql/
    
  solr:
    container_name: solr
    image: ckan/solr:latest
    build: 
      context: ./solr/
      
  redis:
    container_name: redis
    image: redis:latest
